namespace ZeroAlloc.EventSourcing;

/// <summary>
/// Maps event type name strings to CLR types for deserialization.
/// Implementations are source-generated by ZeroAlloc.EventSourcing.Generators.
/// </summary>
public interface IEventTypeRegistry
{
    /// <summary>Tries to resolve a CLR type from a stored event type name.</summary>
    bool TryGetType(string eventType, out Type? type);

    /// <summary>Returns the stored event type name for a given CLR type.</summary>
    string GetTypeName(Type type);
}
