using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace ZeroAlloc.EventSourcing;

/// <summary>
/// Extension methods for registering ZeroAlloc.EventSourcing services.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Registers ZeroAlloc.EventSourcing core services and returns a builder
    /// for configuring adapter-specific services.
    /// </summary>
    /// <remarks>
    /// Registers <see cref="ZeroAllocEventSerializer"/> as <see cref="IEventSerializer"/>
    /// using <c>TryAddSingleton</c>. Register your own <see cref="IEventSerializer"/> before
    /// calling this method to opt out of the default.
    /// <para>
    /// To use the default serializer you must also register <c>ISerializerDispatcher</c> — call
    /// <c>services.AddSerializerDispatcher()</c> (generated by ZeroAlloc.Serialisation).
    /// </para>
    /// </remarks>
    public static EventSourcingBuilder AddEventSourcing(this IServiceCollection services)
    {
        services.TryAddSingleton<IEventSerializer, ZeroAllocEventSerializer>();
        return new EventSourcingBuilder(services);
    }

    /// <summary>
    /// Registers <see cref="InMemoryCheckpointStore"/> as <see cref="ICheckpointStore"/>.
    /// </summary>
    public static EventSourcingBuilder UseInMemoryCheckpointStore(this EventSourcingBuilder builder)
    {
        builder.Services.TryAddSingleton<ICheckpointStore, InMemoryCheckpointStore>();
        return builder;
    }
}
