using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace ZeroAlloc.EventSourcing;

/// <summary>
/// Extension methods for registering ZeroAlloc.EventSourcing services.
/// </summary>
public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Registers ZeroAlloc.EventSourcing services on <paramref name="services"/>.
    /// </summary>
    /// <remarks>
    /// By default registers <see cref="ZeroAllocEventSerializer"/> as <see cref="IEventSerializer"/>
    /// using <c>TryAddSingleton</c>. Register your own <see cref="IEventSerializer"/> before calling
    /// this method to opt out of the default.
    /// <para>
    /// To use the default serializer you must also register <c>ISerializerDispatcher</c> — call
    /// <c>services.AddSerializerDispatcher()</c> (generated by ZeroAlloc.Serialisation in your assembly).
    /// </para>
    /// </remarks>
    /// <param name="services">The service collection to configure.</param>
    /// <returns><paramref name="services"/> for chaining.</returns>
    public static IServiceCollection AddEventSourcing(this IServiceCollection services)
    {
        services.TryAddSingleton<IEventSerializer, ZeroAllocEventSerializer>();
        return services;
    }
}
