// src/ZeroAlloc.EventSourcing.Generators/EventTypeRegistryGenerator.cs
using Microsoft.CodeAnalysis;
using System.Text;

namespace ZeroAlloc.EventSourcing.Generators;

/// <summary>
/// Roslyn incremental source generator that emits an <c>IEventTypeRegistry</c> implementation
/// for each aggregate discovered by <see cref="AggregateDispatchGenerator"/>.
/// </summary>
[Generator]
public sealed class EventTypeRegistryGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Reuse the same aggregate discovery as AggregateDispatchGenerator
        var aggregates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => AggregateDispatchGenerator.IsPartialClassWithBase(node),
                transform: static (ctx, _) => AggregateDispatchGenerator.GetAggregateInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(aggregates, static (ctx, info) =>
        {
            var source = EmitRegistry(info);
            // Qualify hint name with namespace to avoid collisions
            var hint = string.IsNullOrEmpty(info.Namespace)
                ? $"{info.ClassName}EventTypeRegistry.g.cs"
                : $"{info.Namespace}.{info.ClassName}EventTypeRegistry.g.cs";
            ctx.AddSource(hint, source);
        });
    }

    private static string EmitRegistry(AggregateInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using ZeroAlloc.EventSourcing;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>Source-generated <see cref=\"IEventTypeRegistry\"/> for <see cref=\"{info.ClassName}\"/>.</summary>");
        sb.AppendLine($"public sealed class {info.ClassName}EventTypeRegistry : IEventTypeRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<string, Type> _byName = new Dictionary<string, Type>");
        sb.AppendLine("    {");

        for (var i = 0; i < info.EventTypeFullNames.Count; i++)
        {
            sb.AppendLine($"        [\"{info.EventTypeNames[i]}\"] = typeof({info.EventTypeFullNames[i]}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    private static readonly Dictionary<Type, string> _byType = new Dictionary<Type, string>");
        sb.AppendLine("    {");

        for (var i = 0; i < info.EventTypeFullNames.Count; i++)
        {
            sb.AppendLine($"        [typeof({info.EventTypeFullNames[i]})] = \"{info.EventTypeNames[i]}\",");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public bool TryGetType(string eventType, out Type? type) => _byName.TryGetValue(eventType, out type);");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public string GetTypeName(Type type) => _byType.TryGetValue(type, out var name) ? name : type.Name;");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
