using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZeroAlloc.EventSourcing.Generators;

/// <summary>
/// Roslyn incremental source generator that emits a type-switch <c>ApplyTyped</c> method
/// for every <c>partial</c> class that inherits <c>Projection&lt;TReadModel&gt;</c>.
/// The generator scans for private/protected Apply methods with signature Apply(TReadModel, TEvent)
/// and emits a dispatch switch expression to eliminate manual switch expressions and reflection at runtime.
/// </summary>
[Generator]
public sealed class ProjectionDispatchGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projections = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPartialClassWithBaseSyntax(node),
                transform: static (ctx, _) => GetProjectionInfoPublic(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(projections, static (ctx, info) =>
        {
            var source = EmitApplyTyped(info);
            // Qualify the hint name with the namespace to avoid collisions when two projections share a short name.
            var hint = string.IsNullOrEmpty(info.Namespace)
                ? $"{info.ClassName}.ApplyTyped.g.cs"
                : $"{info.Namespace}.{info.ClassName}.ApplyTyped.g.cs";
            ctx.AddSource(hint, source);
        });
    }

    /// <summary>Syntactic predicate: returns true for partial class declarations with a base type list.</summary>
    private static bool IsPartialClassWithBaseSyntax(SyntaxNode node)
        => node is ClassDeclarationSyntax cls
            && cls.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))
            && cls.BaseList?.Types.Count > 0;

    /// <summary>
    /// Semantic transform: returns a <see cref="ProjectionInfo"/> for classes that inherit
    /// <c>Projection&lt;TReadModel&gt;</c> and have <c>Apply(TReadModel, TEvent)</c> methods.
    /// Returns <c>null</c> for non-projection classes or those without Apply methods.
    /// </summary>
    private static ProjectionInfo? GetProjectionInfoPublic(GeneratorSyntaxContext ctx)
    {
        var cls = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(cls) as INamedTypeSymbol;
        if (symbol is null) return null;

        // Walk base types to find Projection<TReadModel>
        var baseType = symbol.BaseType;
        INamedTypeSymbol? projectionType = null;
        while (baseType is not null)
        {
            if (baseType.OriginalDefinition.ToDisplayString() == "ZeroAlloc.EventSourcing.Projection<TReadModel>")
            {
                projectionType = baseType;
                break;
            }
            baseType = baseType.BaseType;
        }
        if (projectionType is null || projectionType.TypeArguments.Length < 1) return null;

        baseType = projectionType;

        var readModelType = baseType.TypeArguments[0] as INamedTypeSymbol;
        if (readModelType is null) return null;

        // Find Apply methods with signature Apply(TReadModel, TEvent)
        // that are private or protected (user-defined dispatch methods).
        var applyMethods = symbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m.Name == "Apply"
                     && m.Parameters.Length == 2
                     && m.ReturnType.Equals(readModelType, SymbolEqualityComparer.Default)
                     && m.Parameters[0].Type.Equals(readModelType, SymbolEqualityComparer.Default)
                     && (m.DeclaredAccessibility == Accessibility.Private
                      || m.DeclaredAccessibility == Accessibility.Protected))
            .Select(m => new ApplyMethodInfo(
                m.Parameters[1].Type.Name,
                m.Parameters[1].Type.ToDisplayString()))
            .Distinct()
            .ToList();

        if (applyMethods.Count == 0) return null;

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();

        return new ProjectionInfo(
            ns,
            symbol.Name,
            readModelType.Name,
            readModelType.ToDisplayString(),
            applyMethods);
    }

    private static string EmitApplyTyped(ProjectionInfo info)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {info.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Auto-generated dispatch method emitted by ProjectionDispatchGenerator.");
        sb.AppendLine($"    /// Routes typed events to the corresponding Apply method overload.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    private {info.ReadModelTypeFullName} ApplyTyped({info.ReadModelTypeFullName} current, object @event)");
        sb.AppendLine("        => @event switch");
        sb.AppendLine("        {");

        for (var i = 0; i < info.ApplyMethods.Count; i++)
        {
            var method = info.ApplyMethods[i];
            sb.AppendLine($"            {method.EventTypeFullName} __e => Apply(current, __e),");
        }

        sb.AppendLine("            _ => current");
        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
