//HintName: EventSourcingMediatorGenerated.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ZeroAlloc.EventSourcing;
using ZeroAlloc.Mediator;

namespace ZeroAlloc.EventSourcing.Mediator.Generated
{
    internal sealed class GeneratedNotificationDispatcher : ZeroAlloc.EventSourcing.Mediator.INotificationDispatcher
    {
        private readonly IMediator _mediator;

        public GeneratedNotificationDispatcher(IMediator mediator)
        {
            _mediator = mediator;
        }

        public ValueTask DispatchAsync(object @event, CancellationToken ct) => @event switch
        {
            global::MyApp.UserCreated __evt => _mediator.Publish(__evt, ct),
            _ => ValueTask.CompletedTask
        };
    }
}

namespace ZeroAlloc.EventSourcing.Mediator
{
    internal static class EventSourcingBuilderMediatorExtensions
    {
        /// <summary>
        /// Registers a per-stream <see cref="EventStoreMediatorBridge"/> as <see cref="IHostedService"/>.
        /// LIVE events implementing <see cref="INotification"/> are published via <see cref="IMediator.Publish"/>;
        /// history replays are filtered positionally (subscription from <see cref="StreamPosition.End"/>).
        /// </summary>
        public static EventSourcingBuilder PublishViaMediator(this EventSourcingBuilder builder, StreamId streamId)
        {
            builder.Services.AddSingleton<IHostedService>(sp =>
                new EventStoreMediatorBridge(
                    sp.GetRequiredService<IEventStore>(),
                    sp.GetRequiredService<INotificationDispatcher>(),
                    sp.GetRequiredService<ILogger<EventStoreMediatorBridge>>(),
                    streamId));
            builder.Services.TryAddSingleton<INotificationDispatcher, Generated.GeneratedNotificationDispatcher>();
            return builder;
        }
    }
}
