using System.Collections.Immutable;
using System.Text;

namespace ZeroAlloc.EventSourcing.Mediator.Generator;

internal static class DispatcherEmitter
{
    public static string Emit(ImmutableArray<NotificationTypeInfo> notifications)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using ZeroAlloc.EventSourcing;");
        sb.AppendLine("using ZeroAlloc.Mediator;");
        sb.AppendLine();

        // Dispatcher in Generated namespace.
        sb.AppendLine("namespace ZeroAlloc.EventSourcing.Mediator.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed class GeneratedNotificationDispatcher : ZeroAlloc.EventSourcing.Mediator.INotificationDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IMediator _mediator;");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedNotificationDispatcher(IMediator mediator)");
        sb.AppendLine("        {");
        sb.AppendLine("            _mediator = mediator;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public ValueTask DispatchAsync(object @event, CancellationToken ct) => @event switch");
        sb.AppendLine("        {");
        foreach (var n in notifications)
        {
            sb.Append("            ").Append(n.FullyQualifiedName).AppendLine(" __evt => _mediator.Publish(__evt, ct),");
        }
        sb.AppendLine("            _ => ValueTask.CompletedTask");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Full extension method in ZeroAlloc.EventSourcing.Mediator namespace.
        // INTERNAL static class so multiple consuming assemblies don't collide.
        sb.AppendLine("namespace ZeroAlloc.EventSourcing.Mediator");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class EventSourcingBuilderMediatorExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers a per-stream <see cref=\"EventStoreMediatorBridge\"/> as <see cref=\"IHostedService\"/>.");
        sb.AppendLine("        /// LIVE events implementing <see cref=\"INotification\"/> are published via <see cref=\"IMediator.Publish\"/>;");
        sb.AppendLine("        /// history replays are filtered positionally (subscription from <see cref=\"StreamPosition.End\"/>).");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static EventSourcingBuilder PublishViaMediator(this EventSourcingBuilder builder, StreamId streamId)");
        sb.AppendLine("        {");
        sb.AppendLine("            builder.Services.AddSingleton<IHostedService>(sp =>");
        sb.AppendLine("                new EventStoreMediatorBridge(");
        sb.AppendLine("                    sp.GetRequiredService<IEventStore>(),");
        sb.AppendLine("                    sp.GetRequiredService<INotificationDispatcher>(),");
        sb.AppendLine("                    sp.GetRequiredService<ILogger<EventStoreMediatorBridge>>(),");
        sb.AppendLine("                    streamId));");
        sb.AppendLine("            builder.Services.TryAddSingleton<INotificationDispatcher, Generated.GeneratedNotificationDispatcher>();");
        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
